[project]
name = "astrbot_plugin_typst_render"
version = "0.2.1"
description = "An Astrbot Plugin For Typst Rendering"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "astrbot>=3.5.23",
    "typst>=0.13.4",
]
